### ISSUE TITLE
Voter Voting for a candidate

### ISSUE THREAD

**Issue by muondu** [mallimuondu/election-platform#15]
When you are asked to vote for a candidate, if you put spaces, it says good bye.

Solution
For where the input for voting for a candidate, have an if statement that will check if someone has made and if statement

**Comment by mallimuondu** [comment]
pls clarify

**Comment by muondu** [comment]
For the input for asking which candidate you want, if you put a space bar it says good bye

**Comment by mallimuondu** [comment]
done
